---
title: "prelim analysis feedback"
format: html
editor: visual
---

## Preliminary data analysis feedback

### General 
- Pay attention to organization of the project. I'm not sure why the file "Bazuro_Capstone_Final.csv" is in the code folder
- Check your use of "return" and ### spacing for headers - without a return and a space b/w the # and the next word you don't get a heading level. Keep working on sprucing up your Markdown.
- Overall, you did a good job thinking about this data analysis. However, there are quite a few issues you need to address. Read below for details.

### Data Analysis Element Type
Line 116 - please put a clear statement of your null hypothesis and alternative hypotheses (based on your plots that you ran above - you have some expectations about results) above your model. Do you have alternative hypotheses? What (science!) might lead to differences in element levels across these different habitat types?

Line 117 - I think you should include an interaction term in your model. See Chapter 6 (and ask me!) for details. Basically, the idea of an interaction is to say that "I think the effect of habitat on element abundance depends on the element in question"

Line 121 - whether a test is 1-tailed or 2-tailed is not related the number of predictor variables but is instead related to your expected direction of difference. 

Line 126 - You are quite right that your data do not meet the assumption of normality and they have other issues as well. But the solution is not to remove outliers if the outliers seem like valid data and not mistakes. We will talk about a modeling framework `glm` that, unlike `lm`, is less strict to the assumptions of normality. I expect you will need to run a `glm` model for your final analysis.

Line 129 - It is not correct that the non-normal nature of your data means that the points farther from "normal" will have more sway on the model - notice that your leverage plot doesn't look as bad.

Line 147 - Yes - we need to do some multiple comparison of means and we can meet to discuss it or you can work on it in class and I can help there. But please note that what you plotted (good job following the chapter!) is not means and standard DEVIATIONS but means and standard ERRORS. Look closely at your formula on line 154 to show to yourself that sd_Concentration is not acutally a sd measurement.

Take a minute to google the difference between sd and se (sometimes called sem = standard error of the mean).  And think about why you would plot one vs. the other.

Line 170 - I'm not sure I understand what you mean by "they would all be put in relative to one another" and I'm not sure what you mean that the y-axis is weird. The issue seems to mainly be that the seep is the site with the main source of all of these elements.

Some things to take care of on this analysis before final draft:
1. Address non-normality of data
2. Add interaction term to model and think about what it means
3. Run Tukey test on model results
4. Update final figure

### Data Analysis DO per
First, I think we have an issue. Again, I'd like you to think about, scientifically, how the level of DO in water might be likely to influence the concentration of different elements, and, if so, if it would have a similar effect on all of the elements.

You are setting up a regression with element concentration ~ DO but are not accounting for the fact that the element concentration column is for a whole bunch of different elements.

Thus, as far as I see it,  you have 2 choices:
1. Focus on a single element - choose one that you think might be related to DO, and look just at that single element. Run the regression on that filtered data set.

2. Run and ANCOVA where you look at the effect of DO concentration on element abundance, taking into account element type. See the second half of chapter 6 which is all about ANCOVA if you want to go this route.

Regardless, I'd like to see more scientific thinking in the hypothesis section about what you expect to see and why (with why in terms of chemistry or biology).

Line 49 - I don't think your choice to remove outliers is reasonable. You don't have a reason to think that they represent anything other than natural variation. Instead, what you have are data that are not normally distributed so we will likely run your analysis as a `glm` rather than `lm`.

Line 76 - when you look at this plot, you can see what I mean about the role that different elements are playing - those two values up above 600 ppm stood out in your other analysis. So again, I think you need to either focus on a single element or run an ANCOVA.

Line 96 - the autoplot does not identify outliers, so I'm not sure why you noted that there are outliers. However, your Q-Q plot shows some real deviations from normality on the right-side

Line 114 - You have learned quite a bit about plotting, and this is suppossed to be the final "publication ready" figure, so make it nice (esp axis labels!)

To do:
1. Decide if you will focus on one element or run and ANCOVA
2. Address how to deal with non-normality of data (esp glm option)
3. Replace outliers unless there is a better reason to remove them
4. Update final figure.

