<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrew Bazuro">

<title>Final Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Final Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final Report_files/libs/quarto-html/quarto.js"></script>
<script src="Final Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Final Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final Report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final Report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrew Bazuro </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="read-in-dataset-and-packages" class="level1">
<h1>Read in dataset and Packages</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>Stream <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"Bazuro_Capstone_Final.csv"</span>))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Stream2 <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">"Data"</span>, <span class="st">"Bazuro_Capstone_Final2.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="set-up-dataset-for-analysis" class="level2">
<h2 class="anchored" data-anchor-id="set-up-dataset-for-analysis">Set up dataset for analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Stream<span class="sc">$</span>Element <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Stream<span class="sc">$</span>Element) <span class="co">#changes the Element variable into a factor</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Stream<span class="sc">$</span>Type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(Stream<span class="sc">$</span>Type) <span class="co">#changes the Type variable into a factor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The dataset that has been used for this project examines metal concentrations and other abiotic factors in the Seep water of the Wester Brooks Range of Alaska from 2022 to 2023. The study focuses on the Salmon watershed and the community of Kiana which survive off of fish harvested from the watershed. Several nearby watershed were also sampled including Timber Creek, Tukpahlearik Creek, Salmon River, Kallarichuk River, Kobuk River, and Devil’s Lake. It specifically contains measurements of pH, conductivity, dissolved oxygen, and turbidity. The dataset 4,368 rows and 17 columns of data.</p>
<section id="steps-for-analysis" class="level2">
<h2 class="anchored" data-anchor-id="steps-for-analysis">Steps for analysis</h2>
<p>To prepare the dataset for analysis I first loaded it in and made all appropriate variables into factor variables in preparation for tidying. I then filtered out the data so that only the four elements that were necessary for analysis remained. This left the dataset with only the four necessary elements (Fe, K, Na, and Mg) and 832 rows. To prepare for the second analysis I had to filter down to just Fe, which left it with 207 rows.</p>
<section id="outliers" class="level3">
<h3 class="anchored" data-anchor-id="outliers">Outliers</h3>
<p>After filtering the dataset was examined for outliers and issues in normality, of which there were several in the dataset. After removing a few of the concerning outliers the dataset still had issues in normality and far more outliers which appeared to be valid data points even if they were outside of the acceptable range and had been flagged. As such, to solve this issue the analysis was run with a glm model to allow more leeway from the normality assumption. The changed dataset was then saved under the name <code>Bazuro_Capstone_Final.csv</code> and can be found in the <code>data</code> folder. The second analysis used a different dataset that was saved as <code>Bazuro_Capstone_Final2.csv</code> and can also be found in the <code>data</code> folder.</p>
</section>
</section>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="element-type-analysis" class="level2">
<h2 class="anchored" data-anchor-id="element-type-analysis">Element Type Analysis</h2>
<p>The analysis focused on the question: What is the effect of different habitat types on Mg, Na, Fe, and K.</p>
<p>The null hypothesis for the first analysis was “There is no relationship between <code>Element</code>, <code>Type</code>, and the <code>Concentration_ppm</code></p>
<p>The alternative hypothesis for the first analysis was that: “There will be a significant relationship between <code>Element</code>, <code>Type</code>, and <code>Concentration_ppm</code>”</p>
<p>The response variable in this analysis was <code>Concentration_ppm</code> which is a continous variable. The predictor variables were <code>Element</code> and <code>Type</code> which were both categorical variables.</p>
<section id="plot-and-guess-relationships" class="level3">
<h3 class="anchored" data-anchor-id="plot-and-guess-relationships">Plot and Guess relationships</h3>
</section>
</section>
<section id="tab" class="level2 tabset">
<h2 class="tabset anchored" data-anchor-id="tab">Tab</h2>
<section id="mg-plot" class="level4">
<h4 class="anchored" data-anchor-id="mg-plot">Mg Plot</h4>
<p>We already examined the plots for outliers in the Data exploration so I won’t do that here. However, I will still place a histogram here to estimate the means of each section. I will start by examining <code>Mg</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"Mg"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()<span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here I see no outliers and will now create a boxplot to examine the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"Mg"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The mean for most graphs is close to zero, while the median in the seep is closer to 200. As such, I expect to see a significant increase in the seep compared to the other habitat types.</p>
</section>
<section id="na-plot" class="level4">
<h4 class="anchored" data-anchor-id="na-plot">Na Plot</h4>
<p>I will now examine <code>Na</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"Na"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()<span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here I do see some outliers but as I have no evidence that they aren’t valid data points I will move forward.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"Na"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on the means I would estimate there to be several significant differences. Notably, seep_control has a lower mean than all the other habitat types. Tributary, river, and lake all appear to have similar means at 1.8 and most likely won’t be significantly different. However, wetland does have a higher mean of 2.5 and will most likely be significantly different from the other habitat types. Finally, the seep appears to have a mean of 2.3 and should be significantly different from all the types aside from the wetland.</p>
</section>
<section id="k-plot" class="level4">
<h4 class="anchored" data-anchor-id="k-plot">K Plot</h4>
<p>I will now examine <code>K</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"K"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()<span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here the values are extremely close and while there are some outliers I have already trimmed out the ones that aren’t valid data points. As such I will now create a boxplot to examine means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"K"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on this plot I would expect a significant difference between the seep and the other plots as it has a mean around 1 while the rest are all closer to 0.25. I would also expect a significant difference between tributary and the other plots as its outliers should significantly change its mean from the other plots.</p>
</section>
<section id="fe-plot" class="level4">
<h4 class="anchored" data-anchor-id="fe-plot">Fe plot</h4>
<p>I will now examine <code>Fe</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"Fe"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()<span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I see no outliers here so I will now examine the boxplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Stream <span class="sc">|&gt;</span> <span class="fu">filter</span>(Element <span class="sc">==</span> <span class="st">"Fe"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Concentration_ppm))<span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>While there are again some outliers here they shouldn’t be a concern. Based on the means I would expect to see a significant difference in only the seep as it has a mean closer to 150 while the rest are close to 0.</p>
</section>
<section id="create-model" class="level3">
<h3 class="anchored" data-anchor-id="create-model">Create Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">=</span> <span class="fu">glm</span>(Concentration_ppm <span class="sc">~</span> Type <span class="sc">*</span> Element, <span class="at">data =</span> Stream) <span class="do">##concentration_ppm explained by Type + Element. I am using a glm to prepare for any issues in normality as I found several in the exploration. I am also using an interaction term to see if the effect of the habitat or element depends on the other element/habitat in question.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I have chosen to perform a two-way anova here because I want to examine the effects of two categorical predictor variables on one ratio response variable. Since my samples are both independent an Anova is the best test and will be two tailed as I mainly want to see the difference and can perform more analysis to determine the direction of the difference.</p>
</section>
<section id="check-model-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="check-model-assumptions">Check model assumptions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(mod1) <span class="do">## create several plots, including normality and leverage, to examine the assumptions for the data.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are some visible errors in normality here but the glm should account for them so I will move forward.</p>
</section>
<section id="interpret-model" class="level3">
<h3 class="anchored" data-anchor-id="interpret-model">Interpret Model</h3>
<p>I will now run the <code>anova()</code> function to interpret the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: Concentration_ppm

Terms added sequentially (first to last)

             Df Deviance Resid. Df Resid. Dev      F    Pr(&gt;F)    
NULL                           823   40653642                     
Type          5  6355097       818   34298545 43.809 &lt; 2.2e-16 ***
Element       3  3107695       815   31190851 35.705 &lt; 2.2e-16 ***
Type:Element 15  7980804       800   23210047 18.339 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Here we can see that there is a highly significant effect of type and element on the concentration_ppm, as well as a significant interaction between the two main effects. There are 5 df for the type variable because it has 6 levels and we are calcuating n = 6 so df = n - 1 = 5. There are 3 df for element because it has 4 levels and we are calculating n = 4 so df = n - 1 = 3.</p>
<p>I will now run the <code>summary()</code> function to examine how the concentration_ppm compares to the intercept for each habitat/type interaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Concentration_ppm ~ Type * Element, data = Stream)

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   0.93180   76.17422   0.012 0.990243    
Typeriver                    -0.33627   79.38972  -0.004 0.996622    
Typeseep                    286.77074   81.15809   3.533 0.000434 ***
Typeseep_control              0.07803  114.26133   0.001 0.999455    
Typetrib                      2.76928   78.07412   0.035 0.971714    
Typewetland                   2.83875  114.26133   0.025 0.980185    
ElementK                     -0.63014  107.72661  -0.006 0.995334    
ElementMg                     1.26676  107.72661   0.012 0.990621    
ElementNa                     0.60590  107.72661   0.006 0.995514    
Typeriver:ElementK            0.45898  112.27402   0.004 0.996739    
Typeseep:ElementK          -284.67701  114.77487  -2.480 0.013332 *  
Typeseep_control:ElementK    -0.08451  161.58992  -0.001 0.999583    
Typetrib:ElementK            -2.39939  110.41348  -0.022 0.982668    
Typewetland:ElementK         -2.76143  161.58992  -0.017 0.986370    
Typeriver:ElementMg          24.95801  112.35355   0.222 0.824263    
Typeseep:ElementMg          374.94343  114.77487   3.267 0.001134 ** 
Typeseep_control:ElementMg   26.99517  161.58992   0.167 0.867365    
Typetrib:ElementMg           45.52695  110.42702   0.412 0.680244    
Typewetland:ElementMg         0.10374  161.58992   0.001 0.999488    
Typeriver:ElementNa           0.10292  112.27402   0.001 0.999269    
Typeseep:ElementNa         -284.34524  114.77487  -2.477 0.013439 *  
Typeseep_control:ElementNa   -1.07162  161.58992  -0.007 0.994710    
Typetrib:ElementNa           -2.76281  110.42702  -0.025 0.980046    
Typewetland:ElementNa        -1.90860  161.58992  -0.012 0.990579    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 29012.56)

    Null deviance: 40653642  on 823  degrees of freedom
Residual deviance: 23210047  on 800  degrees of freedom
AIC: 10831

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>Our intercept here is the ElementFe predictor which is significantly different from the seep type and the three other elements when they are in the seep.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>phc1 <span class="ot">&lt;-</span> <span class="fu">glht</span>(mod1, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">Type =</span> <span class="st">"Tukey"</span>, <span class="at">Element =</span> <span class="st">"Tukey"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in mcp2matrix(model, linfct = linfct): covariate interactions found --
default contrast might be inappropriate
Warning in mcp2matrix(model, linfct = linfct): covariate interactions found --
default contrast might be inappropriate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(phc1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: Tukey Contrasts


Fit: glm(formula = Concentration_ppm ~ Type * Element, data = Stream)

Linear Hypotheses:
                                    Estimate Std. Error z value Pr(&gt;|z|)    
Type: river - lake == 0             -0.33627   79.38972  -0.004  1.00000    
Type: seep - lake == 0             286.77074   81.15809   3.533  0.00632 ** 
Type: seep_control - lake == 0       0.07803  114.26133   0.001  1.00000    
Type: trib - lake == 0               2.76928   78.07412   0.035  1.00000    
Type: wetland - lake == 0            2.83875  114.26133   0.025  1.00000    
Type: seep - river == 0            287.10700   35.83769   8.011  &lt; 0.001 ***
Type: seep_control - river == 0      0.41429   88.05314   0.005  1.00000    
Type: trib - river == 0              3.10555   28.16510   0.110  1.00000    
Type: wetland - river == 0           3.17502   88.05314   0.036  1.00000    
Type: seep_control - seep == 0    -286.69271   89.65078  -3.198  0.02054 *  
Type: trib - seep == 0            -284.00145   32.82041  -8.653  &lt; 0.001 ***
Type: wetland - seep == 0         -283.93199   89.65078  -3.167  0.02275 *  
Type: trib - seep_control == 0       2.69126   86.86884   0.031  1.00000    
Type: wetland - seep_control == 0    2.76072  120.44202   0.023  1.00000    
Type: wetland - trib == 0            0.06947   86.86884   0.001  1.00000    
Element: K - Fe == 0                -0.63014  107.72661  -0.006  1.00000    
Element: Mg - Fe == 0                1.26676  107.72661   0.012  1.00000    
Element: Na - Fe == 0                0.60590  107.72661   0.006  1.00000    
Element: Mg - K == 0                 1.89690  107.72661   0.018  1.00000    
Element: Na - K == 0                 1.23604  107.72661   0.011  1.00000    
Element: Na - Mg == 0               -0.66086  107.72661  -0.006  1.00000    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
<p>Here we can see that there is a significant effect between seep_control and lake, seep and river, tributary and seep, and wetland and seep.</p>
</section>
<section id="replot-to-show-relationships" class="level3">
<h3 class="anchored" data-anchor-id="replot-to-show-relationships">Replot to show Relationships</h3>
<p>I will now create a plot using the means and std errors of each of the commbinations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sum_stream <span class="ot">&lt;-</span> Stream <span class="sc">|&gt;</span> <span class="fu">group_by</span>(Element, Type) <span class="sc">|&gt;</span> <span class="fu">summarise</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean_Concentration =</span> <span class="fu">mean</span>(Concentration_ppm),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">se_Concentration =</span> <span class="fu">sd</span>(Concentration_ppm)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">n</span>())</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Element'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sum_stream</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 4
# Groups:   Element [4]
   Element Type         mean_Concentration se_Concentration
   &lt;fct&gt;   &lt;fct&gt;                     &lt;dbl&gt;            &lt;dbl&gt;
 1 Fe      lake                      0.932           0.104 
 2 Fe      river                     0.596           0.139 
 3 Fe      seep                    288.             54.7   
 4 Fe      seep_control              1.01            0.751 
 5 Fe      trib                      3.70            0.803 
 6 Fe      wetland                   3.77            1.79  
 7 K       lake                      0.302           0.0520
 8 K       river                     0.424           0.0278
 9 K       seep                      2.40            0.410 
10 K       seep_control              0.295           0.0365
# ℹ 14 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sum_stream, <span class="fu">aes</span>(<span class="at">x =</span> Type, <span class="at">y =</span> mean_Concentration, <span class="at">colour =</span> Element, <span class="at">group =</span> Element)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean_Concentration <span class="sc">-</span> se_Concentration,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">ymax =</span> mean_Concentration <span class="sc">+</span> se_Concentration), <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Mean Concentration Explained by Type and Grouped by Element"</span>, <span class="at">x =</span> <span class="st">"Body of Water"</span>, <span class="at">y =</span> <span class="st">"Mean Concentration (ppm)"</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<p>Overall, we reject the null hypothesis that there was no relationship between <code>Element</code>, <code>Type</code>, and the <code>Concentration_ppm</code>. As we found that the <code>Element</code> (F = 35.705, p = 2.2 E-16) <code>Type</code> (F = 43.809, p = 2.2e -16), and Interaction (F = 18.339, p = 2.2e-16) had a significant and positive effect on the <code>Concentration_ppm</code>. Our specific significant results were between seep_control and lake, seep and river, tributary and seep, and wetland and seep.</p>
</section>
</section>
<section id="do_per-analysis" class="level2">
<h2 class="anchored" data-anchor-id="do_per-analysis">DO_Per Analysis</h2>
<p>The analysis focused on the question: Is there a difference in <code>DO_per</code> for different <code>Concentration_ppm</code> of <code>Fe</code>?</p>
<p>The null hypothesis for the second analysis was “There is no relationship between the <code>Concentration_ppm</code> of <code>Fe</code> and the <code>DO_per</code>.</p>
<p>The alternative hypothesis for the second analysis was “There will be a significant relationship between the <code>Conectration_ppm</code> of <code>Fe</code> and the <code>DO_per</code>.</p>
<p>The response variable was <code>DO_per</code></p>
<section id="plot-and-guess-relationships-1" class="level3">
<h3 class="anchored" data-anchor-id="plot-and-guess-relationships-1">Plot and Guess Relationships</h3>
<p>I will begin by making a boxplot of the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Stream2, <span class="fu">aes</span>(<span class="at">y =</span> DO_per)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 114 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I can see several outliers but there is no reason to doubt that they are valid data so I will leave them in.</p>
<p>I will also make a histogram to check the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> Stream2, <span class="fu">aes</span>(<span class="at">y =</span> DO_per)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 114 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Again while there are outliers I will be leaving them in as they are valid data points and could offer imortant conclusions to my data.</p>
<p>As these are both continuous variables I will create a scatterplot to examine the mean and intercept.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Stream2, <span class="fu">aes</span>(<span class="at">x =</span> DO_per, <span class="at">y =</span> Concentration_ppm)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 114 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here the intercept is near 50 with a negative slope of slope of less than one . However, the large spread leads me to expect that there won’t be a significant association between the two.</p>
</section>
<section id="create-model-1" class="level3">
<h3 class="anchored" data-anchor-id="create-model-1">Create Model</h3>
<p>I will now create the model that I will be using for this analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">=</span> <span class="fu">glm</span>(Concentration_ppm <span class="sc">~</span> DO_per, <span class="at">data =</span> Stream)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I have chosen to use a regression here as I am examining a ratio response variable along with a continous predictor. Since there is only a single predictor a regression is ideal. However, I have chosen to use <code>glm()</code> instead of <code>lm()</code> to deal with any normality issues generated by the outliers.</p>
</section>
<section id="check-model-assumptions-1" class="level3">
<h3 class="anchored" data-anchor-id="check-model-assumptions-1">Check model assumptions</h3>
<p>I will now run the <code>autoplot()</code> function to examine the conditions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As mentioned above the normality issues are present but should be fine with the <code>glm()</code> model that is being used.</p>
</section>
<section id="interpret-model-1" class="level3">
<h3 class="anchored" data-anchor-id="interpret-model-1">Interpret Model</h3>
<p>I will now run the <code>anova()</code> function to interpret the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model: gaussian, link: identity

Response: Concentration_ppm

Terms added sequentially (first to last)

       Df Deviance Resid. Df Resid. Dev      F    Pr(&gt;F)    
NULL                     368    5817529                     
DO_per  1   545665       367    5271864 37.986 1.877e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on this plot I can see that there is a significant association between the DO_per and Concentration_ppm (F = 37.986, p = 1.877e-09)</p>
<p>I will now run the <code>summary()</code> table for closer examination</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Concentration_ppm ~ DO_per, data = Stream)

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 288.0625    42.3786   6.797 4.33e-11 ***
DO_per       -2.8008     0.4544  -6.163 1.88e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 14364.75)

    Null deviance: 5817529  on 368  degrees of freedom
Residual deviance: 5271864  on 367  degrees of freedom
  (455 observations deleted due to missingness)
AIC: 4583.4

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>Here we can see that the slope for this is around -2.8 and the intercept appears to be at 288. This is a steeper plot than my expectations.</p>
</section>
<section id="replot-to-show-relationships-1" class="level3">
<h3 class="anchored" data-anchor-id="replot-to-show-relationships-1">Replot to show Relationships</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Stream2, <span class="fu">aes</span>(<span class="at">x =</span> DO_per, <span class="at">y =</span> Concentration_ppm)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Dissolved Oxygen explained by Concentration of Fe"</span>, <span class="at">x =</span> <span class="st">"Dissolved Oxygen (%)"</span>, <span class="at">y =</span> <span class="st">"Concentration of Fe (ppm)"</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 114 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 114 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Report_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="results-1" class="level3">
<h3 class="anchored" data-anchor-id="results-1">Results</h3>
</section>
</section>
</section>
<section id="challenges" class="level1">
<h1>Challenges</h1>
<section id="overall-challenges" class="level2">
<h2 class="anchored" data-anchor-id="overall-challenges">Overall challenges</h2>
<p>The main part of my project that I had to learn was how to deal with outliers and issues with normality. There was a large number of outliers in my data but the vast majority of them were valid data points which could not be reasonably ignored. As such, my analysis had to be performed in a manner which used a more robust model, which was done through the use of glm.</p>
</section>
<section id="challenges-in-analysis-1" class="level2">
<h2 class="anchored" data-anchor-id="challenges-in-analysis-1">Challenges in analysis 1</h2>
<p>The main difficulties came in how I had to perform a tukeyHSD on a glm with multiple predictor variables. This wasn’t covered in class and required me to dig through the multcomp package to determine the proper code and setup. Even with the information I found in the multcomp package I was only able to make a model with both the predictor variables without the interaction effect. I was also unable to use the <code>cld()</code> function to give myself an easy to read final result to the TukeyHSD as it simply gave an error. This analysis was particularly difficult as it was based off two response variables which required subtle changes to several parts of my analysis as most of the code we learned in class was tailored to use on a single predictor variable. This caused my analysis to run much longer than most of those done in class as I had to check normality and outliers in each of my <code>Element</code> levels.</p>
</section>
<section id="challenges-in-analysis-2" class="level2">
<h2 class="anchored" data-anchor-id="challenges-in-analysis-2">Challenges in analysis 2</h2>
<p>When I started analysis 2 my overall question was very different and had to be trimmed down to a simpler question as due to the structure of the data it would be impossible to look at more than one element without running an ANCOVA, which would be on top of using the glm model to account for the issues in normality.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>